name: pr_to_main

on:
  pull_request:
    branches:
      - main
env:
  DBT_PROFILES_DIR: ./
  DBT_PROJECT_DIR: ./integration_tests

  DBT_GOOGLE_PROJECT: ${{ secrets.DBT_GOOGLE_PROJECT }}
  DBT_GOOGLE_BIGQUERY_DATASET: ${{ secrets.DBT_GOOGLE_BIGQUERY_DATASET }}

  DBT_GOOGLE_BIGQUERY_KEYFILE: /.service-account.json

  DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
  DBT_SNOWFLAKE_USER: ${{ secrets.DBT_SNOWFLAKE_USER }}
  DBT_SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD }}
  DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}
  DBT_SNOWFLAKE_DATABASE: ${{ secrets.DBT_SNOWFLAKE_DATABASE }}
  DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE }}
  DBT_SNOWFLAKE_SCHEMA: ${{ secrets.DBT_SNOWFLAKE_SCHEMA }}

jobs:
  pr_to_main:
    name: pr_to_main
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"

      - name: Install Python packages
        run: |
          pip install pip wheel dbt-core dbt-postgres dbt-bigquery dbt-snowflake

      - name: Authenticate using service account
        run: 'echo "$KEYFILE" > $DBT_GOOGLE_BIGQUERY_KEYFILE'
        shell: bash
        env:
          KEYFILE: ${{ secrets.DBT_GOOGLE_BIGQUERY_KEYFILE }}

      - name: Install dependencies
        run: |
          dbt deps --project-dir $DBT_PROJECT_DIR

      - name: Build dbt models (BigQuery)
        run: dbt build -t bq --project-dir $DBT_PROJECT_DIR

      - name: Build dbt models (Snowflake)
        run: dbt build -t snowflake --project-dir $DBT_PROJECT_DIR

